### ISSUE TITLE
[BUG] contextual-attrs doesn't work

### ISSUE THREAD

**Issue by phongnguyen91** [FabiowQuixada/isml-linter#17] opened 2020-05-13 12:16 UTC
Following this document
https://github.com/FabiowQuixada/isml-linter/blob/master/docs/rules/contextual-attrs.md

The contextual-attrs doesn't work, checked the source code I saw that we should set "contextual-attributes": {} instead of using contextual-attrs

Even I have used "contextual-attributes" but it has thrown other issues
![image](https://user-images.githubusercontent.com/24519031/81811006-25a85d00-954e-11ea-9b6d-a44d9a520179.png)
"Please check if your node version is >=10.0.0. If it is, please report the above issues to https://github.com/FabiowQuixada/isml-linter and add these files to the ignore list while a fix is not available."

My node version 11.15.0
Tested on the repository SFRA https://github.com/SalesforceCommerceCloud/storefront-reference-architecture

**Comment by FabiowQuixada** [comment] 2020-05-15 01:23
Hello @phongnguyen91 , thanks for reporting.
I'll take a look at this and will let you know once there is a fix.
Thank you!

**Comment by FabiowQuixada** [comment] 2020-05-17 16:59
Hello @phongnguyen91 ,

the issue is now fixed, it is available on v5.25.4, please confirm if it works as expected on your side.

Thank you!

**Comment by fabioquixadaosf** [comment] 2020-10-27 23:26
Closing issue due to inactivity.

**Closed by fabioquixadaosf** 2020-10-27 23:26 UTC
Labels: bug, reported fix
