### ISSUE TITLE
🔧 no-trailing-spaces	has wrong link in description

### ISSUE THREAD

**Issue by OleksandrMisiuga** [FabiowQuixada/isml-linter#21] opened 2020-12-10 13:12 UTC
🔧 no-trailing-spaces | Disallows trailing blank spaces forwards to https://github.com/FabiowQuixada/isml-linter/blob/master/docs/rules/no-isscript.md

**Comment by FabiowQuixada** [comment] 2020-12-11 01:36
Thanks for the tip, @OleksandrMisiuga ! The issue is now fixed.
Thanks!

**Closed by FabiowQuixada** 2020-12-11 01:36 UTC
