### ISSUE TITLE
Automatically adding newlines before </textrea>

### ISSUE THREAD

**Issue by jwalshpcis** [FabiowQuixada/isml-linter#39] opened 2022-09-08 14:56 UTC
Hi,

(Please let me know if I'm not raising this issue correctly. This is the first time I'm doing this.)

This code is considered invalid:
```
<div>
    <textarea
        name="text-area"
        value=""
        class="form-control"
        placeholder=" "
        aria-labelledby="text-area-label"
    ></textarea>
</div>
```

This code is considered valid:
```
<div>
    <textarea
        name="text-area"
        value=""
        class="form-control"
        placeholder=" "
        aria-labelledby="text-area-label"
    >
    </textarea>
</div>
```

As well as this code:
```
<div>
    <textarea
        name="text-area"
        value=""
        class="form-control"
        placeholder=" "
        aria-labelledby="text-area-label">
    </textarea>
</div>
```

But they are actually different than the first example, since they contain whitespaces and the first example doesn't. This causes a difference in the rendered html: with the newlines in the isml, the textarea is initialized with empty spaces in the rendered html, but we want it initialized with an empty string.

**Comment by FabiowQuixada** [comment] 2022-09-09 01:50
Hey @jwalshpcis , thanks for reporting! This is the right place, don't worry :D

I have a few questions / notes on the issue:

1. It seems your second and third examples are identical, can you please check you pasted there what you intended?
2. The blank spaces you're talking about are between `>` and `</textarea>`, right?
3. Can you please let me know what specific rule considers the first example invalid?

My understanding is that it refers to the "[one-element-per-line](https://github.com/FabiowQuixada/isml-linter/blob/HEAD/docs/rules/one-element-per-line.md)" rule, and in the docs you can see that the following configuration can be used:

```
"one-element-per-line": {
    except: [] // Possible values: "non-tag" and "iscomment";
}
```
So maybe I can work on adding a "closing-tags" option that would allow the format you pasted in the first example.

Would that fit your needs?

**Comment by jwalshpcis** [comment] 2022-09-09 08:02
Hi @FabiowQuixada, thank you for your responsiveness.

1. I edited my third case (moved the `>` to the previous line)
2. Correct! :)
3. The error I get is `Expected indentation of 4 spaces but found 0` on the line with `></textarea>`. If I move it to the previous line like this: `aria-labelledby="text-area-label"></textarea>` I also get the same error. I assume that this has to do with the `indent` rules, but I see in your documentation that it's deprecated. 

I tested both configurations of the one-element-per-line per line rule, with no success. If you think that it's this rule that causes this validation, let's try that third option!

**Comment by FabiowQuixada** [comment] 2022-09-13 01:54
hey @jwalshpcis , thanks for the info! I'll work on a config for the `indent` rule that will allow the indentation in the first example.

The deprecation you mention is not about the `indent` rule, but about a configuration that is still available in the root of the configuration file.

I'll probably be able to work on it only next week, but I'll let you know as soon as it's ready, ok?

Thanks!

**Comment by jwalshpcis** [comment] 2022-09-13 07:31
Hi @FabiowQuixada , 

Thank you so much for your analysis and your time! I look forward to checking out the result :)

**Comment by jwalshpcis** [comment] 2022-10-28 14:03
Hi, @FabiowQuixada do you have an update on this issue?

**Comment by FabiowQuixada** [comment] 2022-11-14 02:49
hey @jwalshpcis , sorry for the late response, things have been a little rushy these times, I haven't had time to work on this, unfortunatelly. But I'll let you know as soon as things get back to normal and this fix becomes available, ok?

Thanks for your suggestion and also your patience!

**Comment by FabiowQuixada** [comment] 2023-02-21 02:43
hey @jwalshpcis sorry for the delay, but the issue you raised is now fixed, please upgrade ISML Linter to v5.43.4 and let me know if the first case you presented works as expected now.

Thanks!

**Comment by FabiowQuixada** [comment] 2023-05-14 23:35
Hi @jwalshpcis I'm closing this issue due to inactivity. If the issue can still be reproduced, please let me know.

Thanks!

**Closed by FabiowQuixada** 2023-05-14 23:35 UTC
Labels: enhancement

**Comment by jwalshpcis** [comment] 2023-05-30 06:59
Hi @FabiowQuixada! Thanks for the fix.

I tested my scenarios with versions 5.43.4 and 5.43.9 and it now works as expected. Thank you!
