### ISSUE TITLE
isml linter can't recognize custom tag <iscontentasset aid="asset-id" />

### ISSUE THREAD

**Issue by antondyachuk** [FabiowQuixada/isml-linter#10] opened 2019-11-27 14:23 UTC
isml linter throws error "An unexpected error happened while parsing the following templates" for template which includes custom tag **iscontentasset** :
![image](https://user-images.githubusercontent.com/43670463/69731215-2b41f000-1132-11ea-9f06-5a6843f61c95.png)

**Comment by FabiowQuixada** [comment] 2019-11-30 18:01
Hello @antondyachuk ,

thanks for reporting this issue. I tried a simplified version of a template containing multiple <iscontentasset> tags, but I couldn't reproduce it, so I will investigate what might be causing the issue.

Meanwhile, please consider adding the template path to "ignore" attribute on Isml Linter configuration file. I will get back to you once I find and fix the source of the issue.

Thank you!

**Comment by FabiowQuixada** [comment] 2019-12-02 02:34
Also, if you could provide a simplified version of that template that still reproduces the issue, it would be of great help!

**Comment by antondyachuk** [comment] 2019-12-08 22:41
Hi @FabiowQuixada 
Here is full version of the template:
`<footer id="footercontent">
    <div class="container">
        <div class="footer-container row">
            <div class="footer-item col-sm-3 store">
                <iscontentasset aid="footer-locate-store" />
            </div>
            <div class="footer-item col-sm-3 collapsible-xs">
                <iscontentasset aid="footer-account" />
            </div>
            <div class="footer-item col-sm-3 collapsible-xs">
                <iscontentasset aid="footer-support" />
            </div>
            <div class="footer-item col-sm-3 collapsible-xs">
                <iscontentasset aid="footer-about" />
            </div>
        </div>
        <hr class="hidden-xs-down" />
        <div class="row">
            <div class="col-lg-4 col-sm-5 push-sm-7 push-lg-8 social">
                <isslot id="footer-column-m" description="Content in column 1 of the Footer" context="global" />
                <button class="js-back-to-top back-to-top" title="${Resource.msg('button.back_to_top', 'common', null)}" aria-label="${Resource.msg('button.back_to_top', 'common', null)}">
                    <span class="fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-circle fa-inverse fa-stack-2x"></i>
                        <i class="fa fa-arrow-up fa-stack-1x"></i>
                    </span>
                </button>
            </div>
            <div class="col-lg-8 col-sm-7 pull-sm-5 pull-lg-4 copyright-notice">
                <iscontentasset aid="footer-copy" />
            </div>
        </div>
    </div>
</footer>
`

**Comment by FabiowQuixada** [comment] 2019-12-10 00:36
hey @antondyachuk , thanks for that. I still can't reproduce the issue, on my side rules apply as expected.

Can you please confirm if you have ran it on Isml Linter latest version? Also, please check if this is the correct file listed in the output, maybe the actual broken template has a similar path to the one you provided.

**Comment by antondyachuk** [comment] 2019-12-16 21:58
Hi @FabiowQuixada 
I've run linter on version 5.22.2 and there is only one template with name pageFooter.isml. Note, template modules.isml which describes custom tags is present in another cartridge. Is it possible that linter doesn't see modules.isml and throws the error?

**Comment by FabiowQuixada** [comment] 2019-12-25 22:55
hey @antondyachuk ,
although I could not reproduce the issue you mentioned, I could spot a bug related to the "custom-tags" rule, which involves "modules.isml", and it has been fixed on version 5.22.3. I assume you have that rule enabled on your side, so it is possible that the original issue is now fixed.

Please update Isml Linter and let me know the results.

Thanks!

**Comment by FabiowQuixada** [comment] 2020-02-25 16:11
Closing ticket due to inactivity.

**Closed by FabiowQuixada** 2020-02-25 16:11 UTC
Labels: bug
